### ISSUE TITLE
Cade o README

### ISSUE THREAD

**Issue by GCarin1** [henrikbeck95/silverarch#1]
O Cara demora muito para fazer o Readme pessoal

**Comment by henrikbeck95** [comment]
O arquivo atualizado do `README.md` encontra-se disponível na branch `development`, pois ainda não há uma versão estável do projeto, embora já seja possível instalar o sistema operacional em uma máquina. Quando isto ocorrer, o código fonte do projeto estará disponível na branch `main`.
